- name: Run through demo of Data Pipeline environment
  hosts: localhost
  vars:
    namespace: default
    cp_version: 6.1.0
    topic: flogs

  tasks:
  - name: Increase ingest load
    shell: "kubectl -n={{ namespace }} scale deployment flog-producer --replicas=16"

  - name: Pause
    pause:
      prompt: Confirm that the load has increased and press return to continue

  - name: Kill a Kafka pod
    shell: "kubectl -n={{ namespace }} delete pod/confluentkafka-1 --grace-period=0 --force"

  - name: Pause
    pause:
      prompt: Confirm that the failed broker has recovered automatically and press return to continue

  - name: Create historical query consumer group
    shell: |
      cat <<EOF | kubectl apply -f -
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: perf-consumer-query
        namespace: "{{ namespace }}"
        labels:
          app: perf-consumer-query
      spec:
        replicas: 12
        selector:
          matchLabels:
            app: perf-consumer-query
        template:
          metadata:
            labels:
              app: perf-consumer-query
          spec:
            containers:
            - name: consumer
              image: "confluentinc/cp-server:{{ cp_version }}"
              command: ["kafka-consumer-perf-test"]
              args: ["--topic", "{{ topic }}", "--messages", "1000000000000", "--threads", "2", "--broker-list", "confluentkafka:9092", "--group", "{{ topic }}-query", "--timeout", "600000"]
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: "1000m"
            restartPolicy: Always

  - name: Pause
    pause:
      prompt: Confirm that a historical query is running against Kafka/Tiered Storage and press return to continue

  - name: Return load down to a minimal level
    shell: "kubectl -n={{ namespace }} scale deployment flog-producer --replicas=1"
  - name: Stop consumers
    shell: "kubectl -n={{ namespace }} delete deployment.apps/perf-consumer-query"
