apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-confluent-control-center
spec:
  type: NodePort
  ports:
  - port: 9021
    nodePort: 30921
    targetPort: 9021
  selector:
    app: {{ .Release.Name }}-confluent-control-center
