kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ccc-data-claim
  labels:
    app: {{ .Release.Name }}-confluent-control-center
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
