apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: {{ .Release.Name }}-zookeeper
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:{{ .Values.kafka.cpVersion }}
    init: confluentinc/confluent-init-container:2.2.0
  logVolumeCapacity: 10Gi
  dataVolumeCapacity: 10Gi
  storageClass:
    name: {{ .Values.zookeeper.storageclass }}
