kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-es-snap-repo-claim
spec:
  storageClassName: pure-file
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
