kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-kafka-env-config
data:
  KAFKA_ZOOKEEPER_CONNECT: {{ .Release.Name }}-kafka-zk-cs:2181
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
  KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
  KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: {{ .Release.Name }}-kafka:9092
  KAFKA_COMPRESSION_TYPE: producer
  KAFKA_LOG_SEGMENT_BYTES: "104857600"
  KAFKA_LOG_FLUSH_INTERVAL_MS: "1000"
  KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: "1000"
  KAFKA_NUM_PARTITIONS: "12"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "2"
  KAFKA_CONFLUENT_TIER_ENABLE: "true"
  KAFKA_CONFLUENT_TIER_FEATURE: "true"
  KAFKA_CONFLUENT_TIER_BACKEND: S3
  KAFKA_CONFLUENT_TIER_S3_BUCKET: "{{ .Values.kafka.bucket }}"
  KAFKA_CONFLUENT_TIER_S3_REGION: "us-west-2"
  KAFKA_CONFLUENT_TIER_S3_AWS_ENDPOINT_OVERRIDE: "http://{{ .Values.flashblade.datavip }}"
  KAFKA_CONFLUENT_TIER_LOCAL_HOTSET_MS: "0"
  KAFKA_CONFLUENT_TIER_ARCHIVER_NUM_THREADS: "8"
  KAFKA_CONFLUENT_TIER_FETCHER_NUM_THREADS: "16"
  KAFKA_CONFLUENT_TIER_TOPIC_DELETE_CHECK_INTERVAL_MS: "30000"
  KAFKA_CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: "3"
  KAFKA_CONFLUENT_BALANCER_ENABLE: "true"
  KAFKA_CONFLUENT_BALANCER_THROTTLE_BYTES_PER_SECOND: "10737418240"
