kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s

    scrape_configs:
    - job_name: 'pure_flashblade'
      scrape_timeout: 30s
      metrics_path: /metrics/flashblade
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_endpoint
        - source_labels: [__pure_apitoken]
          target_label: __param_apitoken
        - source_labels: [__address__]
          target_label: instance
        - target_label: __address__
          replacement: 127.0.0.1:9491
      static_configs:
        - targets: [ {{ .Values.flashblade.mgmtvip }} ]   # FlashBlade Management IP address
          labels:
            __pure_apitoken: {{ .Values.flashblade.token }}

  datasource.yml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        url: http://127.0.0.1:9090
