apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-monitoring
  labels:
    app: {{ .Release.Name }}-monitoring
spec:
  clusterIP: None
  ports:
  - name: graf-port
    port: 3000
  - name: prom-port
    port: 9090
  selector:
    app: {{ .Release.Name }}-monitoring
