kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 60s

    scrape_configs:
    - job_name: 'elastic'
      scrape_timeout: 30s
      static_configs:
      - targets: ['{{ .Release.Name }}-elastic-monitoring-svc:9114']
    - job_name: 'kafka'
      scrape_timeout: 30s
      static_configs:
      - targets:
        {{- range untilStep 0 (.Values.kafka.nodecount | int) 1 }}
        - '{{ $.Release.Name }}-kafka-{{ . }}-internal:7778'
        {{- end }}
    - job_name: 'pure_flashblade'
      scrape_timeout: 30s
      metrics_path: /metrics/flashblade
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_endpoint
        - source_labels: [__pure_apitoken]
          target_label: __param_apitoken
        - source_labels: [__address__]
          target_label: instance
        - target_label: __address__
          replacement: 127.0.0.1:9491
      static_configs:
        - targets: [ {{ .Values.flashblade.mgmtvip }} ]   # FlashBlade Management IP address
          labels:
            __pure_apitoken: {{ .Values.flashblade.token }}

  datasource.yml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        url: http://127.0.0.1:9090
