kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-prometheus-claim
  labels:
    app: {{ .Release.Name }}-prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-grafana-claim
  labels:
    app: {{ .Release.Name }}-grafana
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
