apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-delete-s3
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: s3manage
      initContainers:
      - name: delete-buckets
        image: joshuarobinson/s3manage
        args: ["delete", "bucket", "{{ .Release.Name }}-kafka-tiered-storage", "{{ .Release.Name }}-es-snaprepo", "{{ .Release.Name }}-es-ssnaps", "{{ .Release.Name }}-warehouse"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      - name: delete-keys
        image: joshuarobinson/s3manage
        args: ["delete", "user-keys", "--account", "{{ .Release.Name }}", "--k8s-secret", "{{ .Release.Name }}-confluent", "{{ .Release.Name }}-elastic", "{{ .Release.Name }}-warehouse"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      - name: delete-users
        image: joshuarobinson/s3manage
        args: ["delete", "user", "--account", "{{ .Release.Name }}", "{{ .Release.Name }}-confluent", "{{ .Release.Name }}-elastic", "{{ .Release.Name }}-warehouse"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      containers:
      - name: delete-account
        image: joshuarobinson/s3manage
        args: ["delete", "account", "{{ .Release.Name }}"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 2
