apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-grafana
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      initContainers:
      - name: wait
        image: centos:8
        command: ["sh"]
        args: ["-c", "sleep 60"]
        imagePullPolicy: Always
      - name: load-fb-dashboard
        image: centos:8
        command: 
          - "sh"
          - "-c"
          - |
            yum install jq -y
            curl -sS https://raw.githubusercontent.com/PureStorage-OpenConnect/pure-exporter/master/extra/grafana/pure-storage-flashblade-system-detail.json --output db.json
            cat db.json | jq 'del(.__inputs)' | jq '{ "dashboard": . }' | jq '.+ {"overwrite": true}' > db2.json;
            curl -X POST -H "Content-Type: application/json" -d @db2.json http://admin:admin@{{ .Release.Name }}-monitoring:3000/api/dashboards/import
        imagePullPolicy: Always
      - name: load-es-dashboard
        image: centos:8
        command: 
          - "sh"
          - "-c"
          - |
            yum install jq -y
            curl -sS https://raw.githubusercontent.com/prometheus-community/elasticsearch_exporter/master/examples/grafana/dashboard.json --output db.json
            cat db.json | jq '{ "dashboard": . }' | jq '.+ {"overwrite": true}' > db2.json;
            curl -X POST -H "Content-Type: application/json" -d @db2.json http://admin:admin@{{ .Release.Name }}-monitoring:3000/api/dashboards/import
      containers:
      - name: terminal
        image: centos:8
        command:
          - "sh"
          - "-c"
          - >
            curl http://admin:admin@{{ .Release.Name }}-monitoring:3000/api/org/
      restartPolicy: Never
  backoffLimit: 2
