apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-install-s3
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: s3manage
      initContainers:
      - name: plumb-account
        image: joshuarobinson/s3manage
        args: ["create", "account", "{{ .Release.Name }}"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      - name: plumb-user
        image: joshuarobinson/s3manage
        args: ["create", "user", "--account", "{{ .Release.Name }}", "{{ .Release.Name }}"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      containers:
      - name: plumb-keys
        image: joshuarobinson/s3manage
        args: ["create", "user-key", "--account", "{{ .Release.Name }}", "--k8s-secret", "{{ .Release.Name }}"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      - name: plumb-{{ .Values.kafka.bucket }}
        image: joshuarobinson/s3manage
        args: ["create", "bucket", "--account", "{{ .Release.Name }}", "{{ .Values.kafka.bucket }}"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      - name: plumb-{{ .Values.elasticsearch.bucket }}
        image: joshuarobinson/s3manage
        args: ["create", "bucket", "--account", "{{ .Release.Name }}", "{{ .Values.elasticsearch.bucket }}"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 2
