apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-install-s3
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: s3manage
      initContainers:
      - name: create-account
        image: joshuarobinson/s3manage
        args: ["create", "account", "{{ .Release.Name }}"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      - name: create-users
        image: joshuarobinson/s3manage
        args: ["create", "user", "--account", "{{ .Release.Name }}", "{{ .Release.Name }}-elastic", "{{ .Release.Name }}-confluent", "{{ .Release.Name }}-warehouse"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      containers:
      - name: create-keys
        image: joshuarobinson/s3manage
        args: ["create", "user-key", "--account", "{{ .Release.Name }}", "--k8s-secret", "{{ .Release.Name }}-elastic", "{{ .Release.Name }}-confluent", "{{ .Release.Name }}-warehouse"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      - name: create-buckets
        image: joshuarobinson/s3manage
        args: ["create", "bucket", "--account", "{{ .Release.Name }}", "{{ .Release.Name }}-kafka-tiered-storage", "{{ .Release.Name }}-es-snaprepo", "{{ .Release.Name }}-es-ssnaps", "{{ .Release.Name }}-warehouse"] 
        env:
          - name: PUREFB_URL
            value: {{ .Values.flashblade.mgmtvip }}
          - name: PUREFB_API
            value: {{ .Values.flashblade.token }}
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 2
