apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: s3manage-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
