apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-zk-hs
  labels:
    app: {{ .Release.Name }}-kafka-zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-kafka-zk
